Add missing type annotations
adafruit/Adafruit_CircuitPython_IRRemote pull request #63
Opened 2023-04-25 04:50 UTC by pedrovs16

Fixing to issue #50

2023-04-25 12:17 UTC, FoamyGuy requested changes
Thanks for working on this. I've noted a few places where there are function arguments that we can add types for.

2023-04-25 12:17 UTC, FoamyGuy commented on adafruit_irremote.py
> +def bin_data(pulses) -> List[List]:
Lets add the type for `pulses` as well. With this first pass we are trying to knock out all function arguments and returns.

From the docstrings below it looks like `pulses` is expected to be a List.

2023-04-25 12:17 UTC, FoamyGuy commented on adafruit_irremote.py
> +def decode_bits(pulses) -> NamedTuple:
Same here, lets add type for `pulses`

2023-04-25 12:17 UTC, FoamyGuy commented on adafruit_irremote.py
> +    def __init__(self, pulses, max_pulse=10_000) -> None:
`pulses`, and `max_pulse` here can have types as well. The number one on max_pulse I think is still an int even though it has the underscore in it. Not positive though.

2023-04-25 12:17 UTC, FoamyGuy commented on adafruit_irremote.py
> +    def bin_data(self, pulses) -> List[List]:  # pylint: disable=no-self-use
another `pulses` argument that can be typed.

2023-04-25 12:17 UTC, FoamyGuy commented on adafruit_irremote.py
> +    def decode_bits(self, pulses) -> Tuple:  # pylint: disable=no-self-use
`pulses` argument here can be typed

2023-04-25 12:17 UTC, FoamyGuy commented on adafruit_irremote.py
>          self, input_pulses, max_pulse=10000, pulse_window=0.10
the arguments `input_pulses`, `max_pulse` and `pulse_window` here can be typed.

2023-04-25 12:17 UTC, FoamyGuy commented on adafruit_irremote.py
>          blocking_delay=0.10,
All of the arguments of the read_pulses() function can be typed in the definition of that function here.

2023-04-25 12:17 UTC, FoamyGuy commented on adafruit_irremote.py
> +    def __init__(self, header, one, zero, trail, *, debug=False) -> None:
`header`, `one`, `zero`, `trail` and `debug` arguments here can be typed.

2023-04-25 12:17 UTC, FoamyGuy commented on adafruit_irremote.py
> +    def transmit(self, pulseout, data, *, repeat=0, delay=0, nbits=None) -> None:
`pulseout`, `data`, `repeat`, `delay`, and `nbits` arguments in this function can be typed.

2023-04-25 17:15 UTC, pedrovs16 commented
Already add missing types

2023-04-25 17:46 UTC, pedrovs16 commented
@kattni  problem with docs and imports?

2023-04-25 18:55 UTC, kattni commented
Thanks @pedrovs16! I requested to be tagged so I can verify the documentation still looks right on RTD with the imports before the initial docstring. I'll look into it following the merge and release.

2023-04-28 22:48 UTC, FoamyGuy requested changes
Thanks for following up. 

I've noted a few more changes after having another look over this. 

The rest is looking good to me beyond the things noted.

2023-04-28 22:48 UTC, FoamyGuy commented on adafruit_irremote.py
> +        self, input_pulses: List, max_pulse: int = 10000, pulse_window: int = 0.10
`pulse_window` looks like `float` I think instead of `int`

2023-04-28 22:48 UTC, FoamyGuy commented on adafruit_irremote.py
> +        blocking_delay: bool = 0.10,
both `pulse_window` and `blocking_delay` look like they can be `float` instead of `bool`

2023-04-28 22:48 UTC, FoamyGuy commented on adafruit_irremote.py
> +        self, header: int, one: int, zero: int, trail: int, *, debug=False
`debug` can be typed as `bool`

2023-04-28 22:48 UTC, FoamyGuy commented on adafruit_irremote.py
> +        nbits: int = None,
for `nbits` since the default value is `None` I think it can be `Optional[int]`

2023-05-12 22:27 UTC, FoamyGuy approved these changes
This looks good to me now. Thanks again for working on it @pedrovs16!

I made one commit with a tweak to us float instead of int for delay. It was typed as float in the sphinx docstring already and I confirmed on a device that passing floats is acceptable.

2023-05-12 22:27 UTC, merged